apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app   
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi-app 
  template:
    metadata:
      labels:
        app: fastapi-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: fastapi
  