apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: fastapi-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: fastapi-app     
  podMetricsEndpoints:
  - port: metrics     
    interval: 30s
    path: /actuator/prometheus
  namespaceSelector:
    matchNames:
    - fastapi-app