apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fastapi-multicluster
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'fastapi-app-{{.name}}'
    spec:
      project: default

      source:
        repoURL: 'https://github.com/Xingyuzxy/fastapi-microservice.git'
        targetRevision: main
        path: k8s/overlays/prod

      destination:
        server: '{{.server}}'
        namespace: ns-prod

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true