apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - path: patch-replicas.yaml
    target:
      kind: Deployment
      name: fastapi-app   

images:
  - name: ghcr.io/xingyuzxy/my-fastapi-app
    newTag: dev-latest